apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::315069654700:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-TtRghdCKdBjV
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::334864977755:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system